### ISSUE TITLE
Plans for State and Writer

### ISSUE THREAD

**Issue by achernyak** [ramda/ramda-fantasy#91]
Are there any plans to implement State and Writer?

**Comment by scott-christopher** [comment]
I've got a `State` implementation locally that I can push up a PR for. Nothing for `Writer`, but I'm happy to look into it too.

**Comment by CrossEye** [comment]
While a Writer seems obviously useful, I'm quite curious to see what a State implementation buys JS users.

**Comment by joneshf** [comment]
`Writer` already exists: https://github.com/ramda/ramda-fantasy/blob/master/src/Tuple.js

**Comment by scott-christopher** [comment]
I've pushed a branch up for `State` if people are interested in having a look. I'll hold off raising a PR until I've finished the docs for it sometime in the next day or so. https://github.com/ramda/ramda-fantasy/compare/master...scott-christopher:state

@CrossEye: I've included the cliché example of a deterministic PRNG using `State` in the docs which might spark some ideas for uses. https://github.com/scott-christopher/ramda-fantasy/blob/state/docs/State.md

The reason I implemented it initially was to have access to a "pure" monad that could be swapped in place of `IO`/`Future` as the interpreter while testing some free monad logic.

**Comment by CrossEye** [comment]
@scott-christopher:
> I've included the cliché example of a deterministic PRNG using State in the docs which might spark some ideas for uses

My question was how these might be of use in Javascript, where mutable local states are a dime a dozen.  Having a special construct that makes it possible to deal with local states is important in languages that prohibit or discourage other forms of state.  But in JS, I'm not sure I see the advantage of the State monad over say, this:

```js
const pnrg = seed => () => {
  seed = (seed * 1103515245 + 12345) & 0x7FFFFFFF;
  return (seed >>> 16) / 0x7FFF;
};

const rng = pnrg(42);
rng(); //=> 0.5823236793115024
rng(); //=> 0.5198217719046602

var rollDie = R.map(n => 1 + ((n * 6) >>> 0), rng);
R.times(rollDie, 10); //=> [6, 5, 5, 5, 4, 1, 1, 2, 2, 6]
```

We also had a Random extension for a while built on a similar notion, although allowing all sorts of seeding mechanisms.  It was created in https://github.com/ramda/ramda/commit/560052586b3e7590bcac718ed2d6e933fd640df7 (https://github.com/ramda/ramda/issues/168) and removed for lack of clear interest in https://github.com/ramda/ramda/commit/992aff2c0ad3fdb57a8289616c839acafcfb3222 (https://github.com/ramda/ramda/pull/590).

I'm not looking to discourage the adoption or usage of this, or even to delay bringing it into R-F, I'm just not clear on the advantages.

**Comment by stoeffel** [comment]
@drboolean created a video about the state monad some time ago. Maybe he found some advantage in having `State` in js. ([a monad a day:state](https://vimeo.com/109984691))

**Comment by scott-christopher** [comment]
I've raised #92 to introduce a `State` type and `StateT` transformer.

@CrossEye, the difference with that example is the mutable vs immutable state. Another use case I'm considering exploring in the near future is using `State` to represent the state object for rendering UI components.

**Comment by joneshf** [comment]
> My question was how these might be of use in Javascript, where mutable local states are a dime a dozen. Having a special construct that makes it possible to deal with local states is important in languages that prohibit or discourage other forms of state. But in JS, I'm not sure I see the advantage of the State monad over say, this:

That example can be written in most languages without a construct like `State`. You don't need `State` to do local mutation when you have something like `STRef` or `IORef` in Haskell, but `State` still exists.

The benefits of using `State` are the same as any other data type that models effects. You get referential transparency, lower cognitive load, better refactoring ability, programming to an interface, etc.

**Comment by DrBoolean** [comment]
Made a small example with state and stateT
https://gist.github.com/DrBoolean/d8cec62d495be6afb605
https://gist.github.com/DrBoolean/352b354a47b97a8cf342
